trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: Cache@2
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
      yarn | "$(Agent.OS)"
      yarn
    path: $(YARN_CACHE_FOLDER)
  displayName: 'Cache Yarn packages'

- script: yarn install --frozen-lockfile
  displayName: 'Yarn install'

- script: ionic build
  displayName: 'Ionic web build'

- script: npx cap add android
  displayName: 'Add Android platform'

- task: Gradle@2
  inputs:
    workingDirectory: android'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'assembleDebug'
  